// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2kfV5D6EFq1bJLPjpkzre3h6_QOb4o0',
    appId: '1:998452037223:web:ed543845738401411036c2',
    messagingSenderId: '998452037223',
    projectId: 'survey-app-a2537',
    authDomain: 'survey-app-a2537.firebaseapp.com',
    storageBucket: 'survey-app-a2537.appspot.com',
    measurementId: 'G-RH2RQ65B1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLRWX1itzmJVPWBdrlYDOTeMbQs47yDY',
    appId: '1:998452037223:android:23aecaff925b40cb1036c2',
    messagingSenderId: '998452037223',
    projectId: 'survey-app-a2537',
    storageBucket: 'survey-app-a2537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu5FOguMyCq7aJRR7lSlTyZXoo6yqQ1uk',
    appId: '1:998452037223:ios:aeceaf0faed2b7f91036c2',
    messagingSenderId: '998452037223',
    projectId: 'survey-app-a2537',
    storageBucket: 'survey-app-a2537.firebasestorage.app',
    iosBundleId: 'com.example.loanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu5FOguMyCq7aJRR7lSlTyZXoo6yqQ1uk',
    appId: '1:998452037223:ios:e5bc8c2e715abd461036c2',
    messagingSenderId: '998452037223',
    projectId: 'survey-app-a2537',
    storageBucket: 'survey-app-a2537.appspot.com',
    iosBundleId: 'com.example.survey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-2kfV5D6EFq1bJLPjpkzre3h6_QOb4o0',
    appId: '1:998452037223:web:a181386ec1653b781036c2',
    messagingSenderId: '998452037223',
    projectId: 'survey-app-a2537',
    authDomain: 'survey-app-a2537.firebaseapp.com',
    storageBucket: 'survey-app-a2537.appspot.com',
    measurementId: 'G-9BXEPYNFN8',
  );
}